### PR TITLE
Add HTML title and css configuration to Redoc/Swagger

### PR DESCRIPTION
**Pull request by BenJeau**
Changes:
- formatted HTML file correctly (added end tags)
- made it possible to change the HTML title and add custom CSS (for styling the docs page)
  - had to pass the variables to the function or else the swagger title/css was shared with redoc 

This should be added in the docs, although unsure how to change them/where they are.

### CODE REVIEW

**Comment by BenJeau** [comment]
I'm coming from JavaScript, where there's this available https://www.npmjs.com/package/swagger-ui-express and looking at the source code, they did something similar https://github.com/scottie1984/swagger-ui-express/blob/master/index.js

There's more that could be made custom, but I think these two are the most important

**Comment by ahopkins** [comment]
The title makes sense, but TBH any much more customization than that and I think the developer should just supply their own HTML. 

```python
self.OAS_PATH_TO_REDOC_HTML
self.OAS_PATH_TO_SWAGGER_HTML
```

**Comment by BenJeau** [comment]
Ok I don't mind, I would personally find it useful for more things to be configurable - although, I would love to at least have HTML title is modifiable.

So I assume you'd rather like the user (dev in this scenario) to provide an HTML file if they'd like to modify what is passed to swagger or how it's called, for example https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L130, I'd like to set some default options, such as the oauth clientId, so I don't need to write it here every time when authenticating (current situation):

image

Which I've been doing in that JavaScript lib by passing the following to their `setup()`:

```js
swaggerOptions: {
  oauth: {
    clientId: "auth-client-id",
  }
}
```

Which just in turn calls a function from swagger (with this as the config https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/)

<hr>

Let me know what you think or like to be done with this PR

**Comment by ahopkins** [comment]
I'm still not 💯 sure...

https://sanic.dev/en/plugins/sanic-ext/configuration.html#swagger-ui-configuration

We do have a configuration for that.

As to what should and should not be config, I guess my point is that I don't want to go too far down the slippery slope. It should be a convenience, for sure. But I don't want to couple our implementation to swagger any more tightly than necessary, provided there is an escape hatch for the dev to do what they need. This is sort of the line that Sanic tries to thread in being a useful set of tools. Granted Sanic Extensions exists to bend the rule more than the core project can.

Happy to hear more of your thoughts, and you may be right that css styling is not too offensive to the concept and should stay.

**Comment by ahopkins** [comment]
Okay, I have been thinking more about this, and I think your solution makes sense. Let's get this ready and included in next week's release.

**Review by ahopkins — APPROVED** [review]

**Comment by ahopkins** [comment]
Looks like you did not enable the flag to allow me to make changes to the branch (which is okay). Can you please pull latest `main` and push?

**Comment by BenJeau** [comment]
I'm sorry again for not being active, let me rebase my branch on `main`

**Comment by ahopkins** [comment]
Some broken tests. Try running tox locally to see what's missing. Likely linting issues.

**Comment by ahopkins** [comment]
Replaced by #159

**Pull request closed without merging**
