### PR TITLE
Add templating extension

### PR DESCRIPTION
**Pull request by ahopkins**
This PR adds a new extension for templating. It will _ONLY_ be loaded if Jinja2 is installed. We look into potentially supporting other templating engines in the future.

If installed, there will be three options for how to build your handlers.

## Option 1 - as decorator

The benefit of this approach is that the templates can be predefined at startup time. This will mean that less fetching needs to happen in the handler, and should therefore be the fastest option.

```python
@app.get("/")
@app.ext.template("foo.html")
async def handler(request: Request):
    return {"seq": ["one", "two"]}
```

## Option 2 - as return object

This is meant to mimic the `text`, `json`, `html`, `file`, etc pattern of core Sanic. It will allow the most customization to the response object since it has direct control of it. Just like in other `HTTPResponse` objects, you can control headers, cookies, etc.

```python
from sanic_ext import render

@app.get("/alt")
async def handler(request: Request):
    return await render("foo.html", context={"seq": ["three", "four"]}, status=400)
```

## Option 3 - hybrid/lazy

In this approach, the template is defined up front and not inside the handler (for performance). Then, the `render` function returns a `LazyResponse` that can be used to build a proper `HTTPResponse` inside the decorator.

```python
from sanic_ext import render
@app.get("/")
@app.ext.template("foo.html")
async def handler(request: Request):
    return await render(context={"seq": ["five", "six"]}, status=400)
```

---

## TODO

- [x] testing
- [x] add templates directory to `reload_dir` when `auto_reload` is on
- [ ] ~add config for running a `livereload` server once https://github.com/sanic-org/sanic/pull/2347 is merged (See https://gist.github.com/ahopkins/b37a458cd37c500fceb62fd22ad6d1d3 for example)~

### CODE REVIEW

**Comment by tuna2134** [comment]
I like option2.
Because it’s sound like flask.

**Comment by ahopkins** [comment]
All three options will be available.

**Comment by tuna2134** [comment]
Ok

**Comment by ahopkins** [comment]
So, after putting a lot of thought and effort into this, I think I need to abandon the livereload option for now. Before we can move forward with this, I need to do some work to migrate how reload works in Sanic. Mainly, I want to move it from `subprocess.Popen` to `multiprocessing`. This will tie in with some more plans we have to make EVERY Sanic server using multiprocessing, and will also have some much needed API features.

**Pull request merged**
