### PR TITLE
Fix bugrisk on openapi body decorator

### PR DESCRIPTION
**Pull request by kijk2869**
There is a problem that the sub-content disappears when using the body decorator due to the validation handler.
I solved it by simply getting information on existing functions.

### CODE REVIEW

**Comment by ahopkins** [comment]
Thanks @kijk2869. Do you think you can post a quick example so we can add to the test suite? Or, better yet, add a unit test for this?

**Review by ahopkins — APPROVED** [review]

**Comment by kijk2869** [comment]
I can't think of an appropriate unit test method for this problem.

The error situation is when using body decorator with the others.

In the case of the following, it moves well.
```python
@openapi.summary("Example")
@openapi.description("Bug Example.")
@openapi.body({"text/plain": str})
async def example(request):
    ...
```

However, summary and description decorator are not applied in the following situations.
```python
@openapi.body({"text/plain": str})
@openapi.summary("Example")
@openapi.description("Bug Example.")
async def example(request):
    ...
```

This is a problem caused by other decorators storing values with function, but the body decorator storing with handler which wraps the function.

https://github.com/sanic-org/sanic-ext/blob/388173081cff8e4c4cf6c3cfcf658708af832a3c/sanic_ext/extensions/openapi/openapi.py#L144

**Comment by ahopkins** [comment]
Got it. Thanks for looking into this.

**Comment by ahopkins** [comment]
I think you need to pull latest `main` into your branch to resolve the test.

**Comment by kijk2869** [comment]
> I think you need to pull latest `main` into your branch to resolve the test.

Done, it is now awaiting workflow approval.

**Pull request merged**
