### PR TITLE
Adds current request to default template context

### PR DESCRIPTION
**Pull request by lllama**
As discussed on Discord, this adds the current `request` to the default template context in Jinja.

### CODE REVIEW

**Comment by ahopkins** [comment]
Thanks for adding this. Can you also create a unit test for each of four possible renderings? https://sanic.dev/en//sanic-ext/templating.html#rendering-a-template-from-a-file

**Comment by lllama** [comment]
Added. Let me know if you want the commits squashed or similar.

**Comment by ahopkins** [comment]
@lllama I do squash commits into `main` so it does not matter.

**Review by ahopkins — APPROVED** [review]

**Comment by ahopkins** [comment]
Thanks @lllama 

When done, take it out of "draft" and I will get it merged in.

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
